name: CI

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    container: silex/emacs:${{ matrix.emacs_version }}-ci
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - "29.4"
          - "30.2"

    steps:
      - uses: actions/checkout@v5

      - name: Run Tests
        run: emacs --batch -L . -l test/test-gen.el -f ert-run-tests-batch-and-exit
